export const Permisssion_Type={
    Global_Get_Users:1,
    Global_Withdrawal_Users:2,
    Global_Get_User_Info:3,
    Global_Edit_User_Info:4,
    Global_View_Committee_Details:5,
    Global_Create_Committee:6,
    Global_Transfer_Committee_Members:7,
    Global_Get_User_Permissions_List:8,
    Global_Grant_Revoke_User_Permissions_Customize:9,
    Global_Get_Group_Permissions:10,
    Global_Grant_Revoke_Group_Permissions:11,
    Global_Create_Group_Customize:12,
    Global_Grant_Revoke_Group_To_User_Customize:13,
    Global_View_Payments:14,
    Global_Modify_Payments:15,
    Global_Edit_Payment_Settings:16,
    Global_View_Accommodations:17,
    Global_Modify_Accommodations:18,
    Global_Cannot_Withdrawal:19,

    Committee_View:20,
    Committee_Get_Members:21,
    Committee_Edit_Info:22,
    Committee_Create_Seats:23,
    Committee_Assign_Seats:24,
    Committee_Create_Reviews:25,
    Committee_Push_Reviews:26,
    Committee_General_Reviewer:27,
    Committee_Cancel_Reviews:28,
    Committee_Create_Review_Template:29,

    FileGroup_Upload_File:30,
    FileGroup_Download_File:31,
}

export const Permisson_List=[
    {name:"空权限"},
    {
        name:"获取全局用户列表",
        value:Permisssion_Type.Global_Get_Users, // 1
        global:true
    },
    {
        name:"允许令代表退会",
        value:Permisssion_Type.Global_Withdrawal_Users, // 2
        global:true,
        prerequisities:[
            Permisssion_Type.Global_Get_Users
        ],
    },
    {
        name:"获取全局用户信息",
        value:Permisssion_Type.Global_Get_User_Info,  // 3
        global:true,
        prerequisities:[
            Permisssion_Type.Global_Get_Users
        ],
    },
    {
        name:"修改全局用户信息",
        value:Permisssion_Type.Global_Edit_User_Info,  // 4
        global:true,
        prerequisities:[
            Permisssion_Type.Global_Get_Users,
            Permisssion_Type.Global_Get_User_Info
        ],
    },
    {
        name:"查看会场信息列表",
        value:Permisssion_Type.Global_View_Committee_Details,  // 5
        prerequisities:[
            Permisssion_Type.Global_Get_Users,
        ],
        global:true,
    },
    {
        name:"创建会场",
        value:Permisssion_Type.Global_Create_Committee,  // 5
        global:true,
        prerequisities:[
            Permisssion_Type.Global_Get_Users,
            Permisssion_Type.Global_View_Committee_Details
        ],
    },
    {
        name:"转移会场成员",
        value:Permisssion_Type.Global_Transfer_Committee_Members, // 6
        global:true,
        prerequisities:[
            Permisssion_Type.Global_Get_Users,
        ],
    },
    {
        name:"获取用户权限列表",
        value:Permisssion_Type.Global_Get_User_Permissions_List, // 7
        global:true,
        prerequisities:[
            Permisssion_Type.Global_Get_Users,
        ]
    },
    {
        name:"为用户独立赋予/移除权限",
        value:Permisssion_Type.Global_Grant_Revoke_User_Permissions_Customize,  //8
        global:true,
        prerequisities:[
            Permisssion_Type.Global_Get_Users,
            Permisssion_Type.Global_Get_User_Permissions_List,
        ]
    },
    {
        name:"获取权限组及其权限列表",
        value:Permisssion_Type.Global_Get_Group_Permissions, //9
        global:true,
    },
    {
        name:"为权限组赋予/移除权限",
        value:Permisssion_Type.Global_Grant_Revoke_Group_Permissions, // 10
        global:true,
        prerequisities:[
            Permisssion_Type.Global_Get_Group_Permissions
        ]
    },
    {
        name:"创建自由权限组",
        value:Permisssion_Type.Global_Create_Group_Customize,  // 11
        global:true,
        prerequisities:[
            Permisssion_Type.Global_Get_Group_Permissions
        ]
    },
    {
        name:"为用户赋予/移除自由权限组",
        value:Permisssion_Type.Global_Grant_Revoke_Group_To_User_Customize, // 12
        global:true,
        prerequisities:[
            Permisssion_Type.Global_Get_Users,
            Permisssion_Type.Global_Get_Group_Permissions
        ]
    },
    {
        name:"查看账单",
        value:Permisssion_Type.Global_View_Payments,// 13
        global:true,
    },
    {
        name:"处理账单",
        value:Permisssion_Type.Global_Modify_Payments,//14
        global:true,
        prerequisities:[
            Permisssion_Type.Global_View_Payments
        ]
    },
    {
        name:"修改支付设置",
        value:Permisssion_Type.Global_Edit_Payment_Settings,//15
        global:true,
    },
    {
        name:"查看住宿安排",
        value:Permisssion_Type.Global_View_Accommodations,//16
        global:true,
    },
    {
        name:"处理住宿安排",
        value:Permisssion_Type.Global_Modify_Accommodations,//17
        global:true,
    },
    {
        name:"不得退会",
        value:Permisssion_Type.Global_Cannot_Withdrawal,//18
        global:true,
    },

    {
        name:"可访问会场",
        value:Permisssion_Type.Committee_View,//19
        committee:true,
        lock:true,
    },
    {
        name:"获取会场成员",
        value:Permisssion_Type.Committee_Get_Members,//20
        committee:true,
        prerequisities:[
            Permisssion_Type.Committee_View,
            Permisssion_Type.Global_Get_Users,
        ]
    },
    {
        name:"修改会场信息",
        value:Permisssion_Type.Committee_Edit_Info,//21
        committee:true,
        prerequisities:[
            Permisssion_Type.Committee_View,
            Permisssion_Type.Global_View_Committee_Details
        ]
    },
    {
        name:"创建席位",
        value:Permisssion_Type.Committee_Create_Seats,//22
        committee:true,
        prerequisities:[
            Permisssion_Type.Committee_View 
        ]
    },
    {
        name:"分配席位",
        value:Permisssion_Type.Committee_Assign_Seats,//23
        committee:true,
        prerequisities:[
            Permisssion_Type.Committee_View,
            Permisssion_Type.Committee_Get_Members
        ]
    },
    {
        name:"创建学测",
        value:Permisssion_Type.Committee_Create_Reviews,//24
        committee:true,
        prerequisities:[
            Permisssion_Type.Committee_View,
            Permisssion_Type.Committee_Get_Members
        ]
    },
    {
        name:"推送学测",
        value:Permisssion_Type.Committee_Push_Reviews,//25
        committee:true,
        prerequisities:[
            Permisssion_Type.Committee_View 
        ]
    },
    {
        name:"会场学测官",
        value:Permisssion_Type.Committee_General_Reviewer,//26
        committee:true,
        prerequisities:[
            Permisssion_Type.Committee_View,
        ]
    },
    {
        name:"关闭学测",
        value:Permisssion_Type.Committee_Cancel_Reviews,//27
        committee:true,
        prerequisities:[
            Permisssion_Type.Committee_View 
        ]
    },
    {
        name:"创建学测模板",
        value:Permisssion_Type.Committee_Create_Review_Template,//28
        committee:true,
        prerequisities:[
            Permisssion_Type.Committee_View 
        ]
    },

    {
        name:"向文件组上传文件",
        value:Permisssion_Type.FileGroup_Upload_File,// 29
        filegroup:true,
    },
    {
        name:"从文件组下载文件",
        value:Permisssion_Type.FileGroup_Download_File,// 30
        filegroup:true,
        lock:true,
    },
]
